#include "ft_printf.h"
#include <stdio.h>
#include <limits.h>

int main(void)
{
    int len;
    // printf("---------------------------\n");
    // printf("%d\n", 2147483648);
    // printf("%i\n", 2147483648);
    // printf("%d\n", LONG_MAX - 2147483647);
    // printf("---------------------------\n");
    //len = printf("%#d", 1);
    //printf("\n%d\n", len);
    // printf("%+d\n", -1);
    // printf("%05c\n", 'c');
    // printf("%05s\n", "str");

//--------------------------------------------//

    // printf("---------- flags ----------\n");
    // printf("%x\n", 10);
    // printf("%d\n", -10);
    // printf("%#x\n", -10);
    // // printf("%#d\n", 0x5);
    // printf("%#x\n", 10);
    // printf("%#X\n", 10);
    // printf("---------------------------\n");

//--------------------------------------------//

//     printf("%*d\n", -5, 42);

    // printf("---------- width ----------\n");
    // printf("(01) %*d\n", 5, 42);
    // printf("(02) %*d\n", -5, 42);
    // printf("(03) %-*d\n", 5, 42);
    // printf("(04) %*d\n", 5, 42);
    // printf("(05) %5d\n", 42);
    // printf("(06) %-5d\n", 42);
    // printf("(07) %0*d\n", -5, 42);
    // printf("(08) %0*d\n", 5, 42);
    // printf("(09) %03d\n", 1);
    // printf("(10) %-3d\n", 1);
    // printf("---------------------------\n");
    // ft_printf("(01) %*d\n", 5, 42);
    // ft_printf("(02) %*d\n", -5, 42);
    // ft_printf("(03) %-*d\n", 5, 42);
    // ft_printf("(04) %*d\n", 5, 42);
    // ft_printf("(05) %5d\n", 42);
    // ft_printf("(06) %-5d\n", 42);
    // ft_printf("(07) %0*d\n", -5, 42);
    // ft_printf("(08) %0*d\n", 5, 42);
    // ft_printf("(09) %03d\n", 1);
    // ft_printf("(10) %-3d\n", 1);
    // ft_printf("---------------------------\n");

// //--------------------------------------------//

    printf("-------- precision --------\n");
    printf("%.c\n", 'a');
	printf("%.5c\n", 'a');
	printf("%.p\n", 10);
    printf("%.5p\n", 10);
	printf("%.s\n", "abc");
    printf("%.2s\n", "abc");
	printf("%.5s\n", "abc");
    printf("---------------------------\n");
    ft_printf("%.c\n", 'a');
	ft_printf("%.5c\n", 'a');
	ft_printf("%.p\n", 10);
    ft_printf("%.5p\n", 10);
	ft_printf("%.s\n", "abc");
    ft_printf("%.2s\n", "abc");
	ft_printf("%.5s\n", "abc");
    printf("---------------------------\n");


    printf("-------- char/str ---------\n");
    printf("%10s\n", "abcd");
    printf("%3s\n", "abcd");
    printf("%-10s\n", "abcd");
    printf("%-3s\n", "abcd");
    printf("%.10s\n", "abcd");
    printf("%.3s\n", "abcd");
    printf("%.3s\n", "abcd");
    printf("---------------------------\n");
    ft_printf("%10s\n", "abcd");
    ft_printf("%3s\n", "abcd");
    ft_printf("%-10s\n", "abcd");
    ft_printf("%-3s\n", "abcd");
    ft_printf("%.10s\n", "abcd");
    ft_printf("%.3s\n", "abcd");
    ft_printf("%.3s\n", "abcd");
    printf("---------------------------\n");

    printf("-----------------------------\n");
    len = printf("|%10c|\n", 'a') - 3;
    printf("len : %d\n", len);
    len = printf("|%10s|\n", "abc") - 3;
    printf("len : %d\n", len);
    len = printf("|%10d|\n", 42) - 3;
    printf("len : %d\n", len);
    len = printf("|%10i|\n", 42) - 3;
    printf("len : %d\n", len);
    len = printf("|%10u|\n", 42) - 3;
    printf("len : %d\n", len);
    len = printf("|%10x|\n", 42) - 3;
    printf("len : %d\n", len);
    len = printf("|%10X|\n", 42) - 3;
    printf("len : %d\n", len);
    len = printf("|%10p|\n", (void *)42) - 3;
    printf("len : %d\n", len);
    printf("-----------------------------\n");
    len = ft_printf("|%10c|\n", 'a') - 3;
    printf("len : %d\n", len);
    len = ft_printf("|%10s|\n", "abc") - 3;
    printf("len : %d\n", len);
    len = ft_printf("|%10d|\n", 42) - 3;
    printf("len : %d\n", len);
    len = ft_printf("|%10i|\n", 42) - 3;
    printf("len : %d\n", len);
    len = ft_printf("|%10u|\n", 42) - 3;
    printf("len : %d\n", len);
    len = ft_printf("|%10x|\n", 42) - 3;
    printf("len : %d\n", len);
    len = ft_printf("|%10X|\n", 42) - 3;
    printf("len : %d\n", len);
    len = ft_printf("|%10p|\n", (void *)42) - 3;
    printf("len : %d\n", len);
    printf("-----------------------------\n");

    // ------ width & precision ------
    printf("-----------------------------\n");
    printf("-----------------------------\n");
    printf("10.1\n");
    len = printf("|%10.1c|\n", 'a') - 3;
    printf("    len : %d\n", len);
    len = printf("|%10.1s|\n", "abc") - 3;
    printf("    len : %d\n", len);
    len = printf("|%10.1d|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = printf("|%10.1i|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = printf("|%10.1u|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = printf("|%10.1x|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = printf("|%10.1X|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = printf("|%10.1p|\n", (void *)42) - 3;
    printf("    len : %d\n", len);
    printf("-----------------------------\n");
    printf("1.10\n");
    len = printf("|%1.10c|\n", 'a') - 3;
    printf("    len : %d\n", len);
    len = printf("|%1.10s|\n", "abc") - 3;
    printf("    len : %d\n", len);
    len = printf("|%1.10d|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = printf("|%1.10i|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = printf("|%1.10u|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = printf("|%1.10x|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = printf("|%1.10X|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = printf("|%1.10p|\n", (void *)42) - 3;
    printf("    len : %d\n", len);
    printf("-----------------------------\n");
    printf("1.1\n");
    len = printf("|%1.1c|\n", 'a') - 3;
    printf("    len : %d\n", len);
    len = printf("|%1.1s|\n", "abc") - 3;
    printf("    len : %d\n", len);
    len = printf("|%1.1d|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = printf("|%1.1i|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = printf("|%1.1u|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = printf("|%1.1x|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = printf("|%1.1X|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = printf("|%1.1p|\n", (void *)42) - 3;
    printf("    len : %d\n", len);
    printf("-----------------------------\n");
    printf("10.10\n");
    len = printf("|%10.10c|\n", 'a') - 3;
    printf("    len : %d\n", len);
    len = printf("|%10.10s|\n", "abc") - 3;
    printf("    len : %d\n", len);
    len = printf("|%10.10d|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = printf("|%10.10i|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = printf("|%10.10u|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = printf("|%10.10x|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = printf("|%10.10X|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = printf("|%10.10p|\n", (void *)42) - 3;
    printf("    len : %d\n", len);

    // ------ width & precision ------
    printf("-----------------------------\n");
    printf("-----------------------------\n");
    printf("10.1\n");
    len = ft_printf("|%10.1c|\n", 'a') - 3;
    printf("    len : %d\n", len);
    len = ft_printf("|%10.1s|\n", "abc") - 3;
    printf("    len : %d\n", len);
    len = ft_printf("|%10.1d|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = ft_printf("|%10.1i|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = ft_printf("|%10.1u|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = ft_printf("|%10.1x|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = ft_printf("|%10.1X|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = ft_printf("|%10.1p|\n", (void *)42) - 3;
    printf("    len : %d\n", len);
    printf("-----------------------------\n");
    printf("1.10\n");
    len = ft_printf("|%1.10c|\n", 'a') - 3;
    printf("    len : %d\n", len);
    len = ft_printf("|%1.10s|\n", "abc") - 3;
    printf("    len : %d\n", len);
    len = ft_printf("|%1.10d|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = ft_printf("|%1.10i|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = ft_printf("|%1.10u|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = ft_printf("|%1.10x|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = ft_printf("|%1.10X|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = ft_printf("|%1.10p|\n", (void *)42) - 3;
    printf("    len : %d\n", len);
    printf("-----------------------------\n");
    printf("1.1\n");
    len = ft_printf("|%1.1c|\n", 'a') - 3;
    printf("    len : %d\n", len);
    len = ft_printf("|%1.1s|\n", "abc") - 3;
    printf("    len : %d\n", len);
    len = ft_printf("|%1.1d|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = ft_printf("|%1.1i|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = ft_printf("|%1.1u|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = ft_printf("|%1.1x|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = ft_printf("|%1.1X|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = ft_printf("|%1.1p|\n", (void *)42) - 3;
    printf("    len : %d\n", len);
    printf("-----------------------------\n");
    printf("10.10\n");
    len = ft_printf("|%10.10c|\n", 'a') - 3;
    printf("    len : %d\n", len);
    len = ft_printf("|%10.10s|\n", "abc") - 3;
    printf("    len : %d\n", len);
    len = ft_printf("|%10.10d|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = ft_printf("|%10.10i|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = ft_printf("|%10.10u|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = ft_printf("|%10.10x|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = ft_printf("|%10.10X|\n", 42) - 3;
    printf("    len : %d\n", len);
    len = ft_printf("|%10.10p|\n", (void *)42) - 3;
    printf("    len : %d\n", len);
}